# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'E-Com' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for E-Com
  pod 'Alamofire', '~> 4.7.3'
  pod 'AlamofireObjectMapper', '~> 5.2'
end
